apiVersion: v1
kind: Service
metadata:
  namespace: docfunc
  name: docfunc-app
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30080
  selector:
    app: docfunc-app