apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docfunc
  name: docfunc-app
  labels:
    app: docfunc-app
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: docfunc-app
  template:
    metadata:
      labels:
        app: docfunc-app
    spec:
      containers:
        - name: docfunc-app
          image: nella0128/docfunc-app-amd64
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: docfunc-config
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  key: app_key
                  name: secrets
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql_password
                  name: secrets
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis_password
                  name: secrets
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mail_password
                  name: secrets
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws_access_key_id
                  name: secrets
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws_secret_access_key
                  name: secrets
            - name: RECAPTCHA_SITE_KEY
              valueFrom:
                secretKeyRef:
                  key: recaptcha_site_key
                  name: secrets
            - name: RECAPTCHA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: recaptcha_secret_key
                  name: secrets
            - name: ALGOLIA_APP_ID
              valueFrom:
                secretKeyRef:
                  key: algolia_app_id
                  name: secrets
            - name: ALGOLIA_SECRET
              valueFrom:
                secretKeyRef:
                  key: algolia_secret
                  name: secrets
          ports:
            - containerPort: 9000