apiVersion: v1
kind: Service
metadata:
  namespace: docfunc
  name: mysql-service
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30306
