apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docfunc
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis:latest
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: redis_password
          command:
            - redis-server
          args:
            - --requirepass
            - $(REDIS_PASSWORD)
          ports:
            - containerPort: 6379
