apiVersion: v1
kind: Service
metadata:
  namespace: docfunc
  name: redis-service
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
